CREATE OR REPLACE TABLE CONTACT_TRACER.APP_USER(
APP_USER_ID INT64 NOT NULL,
USER_PASSWORD STRING ,
FIRST_NAME STRING ,
LAST_NAME STRING,
PHONE STRING NOT NULL
);


CREATE OR REPLACE TABLE CONTACT_TRACER.USER(
USER_ID INT64 NOT NULL,
GENDER STRING,
DOB DATE NOT NULL,
INFECTION_STATUS STRING NOT NULL,
ZIPCODE STRING NOT NULL,
LIVING_STATUS STRING,
IMMUNITY_COMPROMISED BOOLEAN NOT NULL,
)


CREATE OR REPLACE TABLE CONTACT_TRACER.HEALTH_TRACK_ADMIN(
ADMIN_ID INT64 NOT NULL,
REG_LAT STRING NOT NULL,
REG_LONG STRING NOT NULL,
QUALIFICATION STRING
)

CREATE OR REPLACE TABLE CONTACT_TRACER.ADDRESS(
ZIPCODE string NOT NULL,
CITY STRING ,
STATE STRING 
)

CREATE OR REPLACE TABLE CONTACT_TRACER.GPS_LOCATION(
GPS_LOC INT64 NOT NULL,
GPS_LAT FLOAT64 ,
GPS_LONG FLOAT64,
DATE DATETIME
);

CREATE OR REPLACE TABLE CONTACT_TRACER.TRAVEL_HISTORY(
COUNTRY STRING NOT NULL,
USER_ID INT64 NOT NULL,
);


CREATE OR REPLACE TABLE CONTACT_TRACER.TRACKER(
TRACKER_ID INT64 NOT NULL,
GPS_LOC INT64 NOT NULL,
USER_ID INT64 NOT NULL
)

CREATE OR REPLACE TABLE CONTACT_TRACER.NOTIFICATION(
NOTIFICATION_ID INT64 NOT NULL,
INFECTION_RISK STRING,
APP_USER_ID INT64 NOT NULL,
);

CREATE OR REPLACE TABLE CONTACT_TRACER.LAB(
LAB_ID INT64 NOT NULL,
LAB_NAME STRING,
ZIPCODE  STRING NOT NULL
)

CREATE OR REPLACE TABLE CONTACT_TRACER.TEST(
TEST_ID INT64 NOT NULL,
TEST_DATE DATE NOT NULL,
TEST_TYPE STRING,
USER_ID INT64 NOT NULL,
LAB_ID INT64 NOT NULL,
RESULT BOOLEAN NOT NULL,
);
